# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ffe6e35970c6336b07b715cb366cd80ed8f5661172e1508490136b29445079e8c1bfc28be0282c0f3ccba81aa10b3b3f745a655ae566ad7f1aa0481c4408da9

test:
  secret_key_base: 05f7c739494effc05f39b23c22e078281c97dde86a6d68ddf6106bc09ad8eba94a7d89a368f03470aab0b47281a6f2c1f2502d5292822116bf3c7e75c0db35d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
